#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 19 09:17:50 2019

@author: abhishekms
"""

# break - used to come out of the loop

count=0
result=0
for i in range(1,10):
  result+=i
  if result>6: #when the result is greter than 6 it will come out of loop
    break
print("result=",result)  #result is 10
 
#continue - used to skip some statements in the loop based on the condition


for cnt in range(1,10):
  if cnt<5:
    continue
  print(cnt)  #prints 5 to 9
  
sum=0
count=0
for num in range(1,10):
  if num>=3 and num<=7: 
    continue
  sum+=num
  print("number=",num)
print("sum=",sum)