#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 15 10:15:34 2019

@author: abhishekms
"""

 
count=1
while count<=3:
  print(count)
  count+=1


for i in range(10):  #prints 0 to 9
  print(i)
  
for i in range(1,11): #prints 1 to 10
  print(i)


for i in range(1,12,2):
  print(i)#1 3 5 7 9 11  
for i in range(1,12,3):
  print(i)   #1 4 7 10
  
for j in range(12,1,-1):
  print(j) # executes loop in backwards 12 to 2
 
#program to find sum of first n natural numbers

n=int(input("enter the value of n"))
sum=0
for i in range(1,n+1):
  sum+=i
print(sum)

sum=0
n=int(input("enter the value of n"))
i=1
while i<=n:
  sum+=i
  i+=1
print(sum)
    