#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 19 08:53:40 2019

@author: abhishekms
"""

#List is an ordered collection of elements

for index in [1,2,3,4]:
  print("hi") #runs 4 times
  print(index)
  
l=[1,2,3,4]
for index in l:
  print("hi\n",index)

l2=[1,2,"hello",8.9,"end"]
for index in l2:
   print("hi\n",index)
   
#program to find sum of elements in a list
cnt=0
avg=0
l3=[1,2,3,4]
sum=0
for i in l3:
  sum+=i
  cnt+=1
avg=sum/cnt
print("sum=",sum)
print("average=",avg)