#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 26 09:04:29 2019

@author: abhishekms
"""

fhand=open('Input.txt') #file will be opened in read mode defaultlly
inp=fhand.read()
print(inp)


fhand=open('Input.txt') 
for line in fhand:  #the loop iterates as many lines are there in the file
  print(line)
  print("*****")

#to print number of lines in a file


fhand=open('Input.txt') 
lines=0
for line in fhand:
  lines+=1
print("number of lines=",lines)


fhand=open('Input.txt') 
inp = fhand.read()
print(inp)
print(len(inp))
print(inp[0:10])
print(inp[::-1])
print(inp[:10:-1])

N = input("enter number of lines")
count=0
