#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb  8 10:20:03 2019

@author: abhishekms
"""

a=10
print(type(a))  #int

b=11.11
print(type(b)) #float

c="abc" #we can declare strings within " " or ' '
print(type(c)) 

d=True
print(type(d)) #bool

print("enter a value")
a=input()
print(a)

s=input("enter a value")
print("value=",s)

msg = "enter a value"
j=input(msg)  
#    j=input(msg) [indentation is important,it will give error]
print(j)

s=input("enter s value")
v=input("enter v value")
d=s+v  # if s=5 & v=7 then outpu 57 bcoz input() takes string as the type of scanned value
print(d)

