#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May  9 12:16:49 2019

@author: abhishekms
"""

a="hello world"
print(max(a)) #compares ASCII val and returns highest value
print(min(a))#print space because ASCII value is small
print(len(a))
l=len("hello")
print(l)


a=int("32") #string converted to integer
print(a)#prints 32
a=a+10
print(a)
b=int(-2.5)
print(b)#prints -2
c=int("hello")
print(c)#ValueError: invalid literal for int() with base 10: 'hello'


d=float(2)
print(d) #prints 2.0

s=str(4.5)
print(s)
print(type(s))#<class 'str'>
