#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 12 09:23:08 2019

@author: abhishekms
"""
'''
a=int(input("enter a value"))
print(a)   #if we type $ --->ValueError: invalid literal for int() with base 10: '$'
So to overcome from this we use try and catch
'''

try:
  a=int(input("enter a value : ")) # if we enter other than integer except block will be executed
  print(a)
except:
  print("enter proper value")
    
try:
  print("enter the operands")
  a=int(input("enter a : "))
  b=int(input("enter b : "))
  c=a/b
  print("c is : ",c)
except:                       #if b is zero then this block will be executed
  print("divide by zero error")